export const data = [
    {
        id:1,
        title:"Music",
        linking:"https://www.youtube.com/watch?v=FLt2TveqHQM",
        sign:"💖"
    },
    {
        id:2,
        title:"Sports",
        linking:"https://www.youtube.com/watch?v=FLt2TveqHQM",
        sign:"💖"
    },
    {
        id:3,
        title:"News",
        linking:"https://www.nintendo.co.uk/Games/Characters-hub/Super-Mario-Hub/Super-Mario-Bros-Hub-Mario-Games-627604.html",
        sign:"💖"
    },
    {
        id:4,
        title:"Movie",
        linking:"https://www.youtube.com/watch?v=FLt2TveqHQM",
        sign:"💖"
    },
    {
        id:5,
        title:"Music",
        linking:"https://www.youtube.com/watch?v=FLt2TveqHQM",
        sign:"💖"
    },
    {
        id:6,
        title:"Sports",
        linking:"https://www.youtube.com/watch?v=FLt2TveqHQM",
        sign:"💖"
    },
    {
        id:7,
        title:"News",
        linking:"https://www.nintendo.co.uk/Games/Characters-hub/Super-Mario-Hub/Super-Mario-Bros-Hub-Mario-Games-627604.html",
        sign:"💖"
    },
    {
        id:8,
        title:"Movie",
        linking:"https://www.youtube.com/watch?v=FLt2TveqHQM",
        sign:"💖"
    }
]